imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

liip_functional_test:
    cache_sqlite_db: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

#doctrine:
#    dbal:
#        driver:   pdo_sqlite
#        path:     :memory:
#        memory:   true
#    orm:
#        auto_generate_proxy_classes: true
#        auto_mapping: true