<?php

namespace Faucon\Bundle\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Faucon\Bundle\ClubBundle\Entity\Club;
use Faucon\Bundle\ClubBundle\Entity\User;
use Faucon\Bundle\ClubBundle\Entity\ClubRelation;

/**
 * ClubRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRelationRepository extends EntityRepository
{
    public function hasLicense(User $user, Club $club)
    {
        return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('cr.hasLicense')
                ->from('FauconClubBundle:ClubRelation', 'cr')
                ->join('cr.user', 'u')
                ->join('cr.club', 'cl')
                ->where('u = ?1')
                ->andWhere('cl = ?2')
                ->setParameter(1, $user)
                ->setParameter(2, $club)
                ->getQuery()
                ->getSingleScalarResult();
    }
}